dist: trusty
import: rubensworks/travis-presets:node-base.yml@master
script:
  - npm run lint
  - npm run production
before_deploy:
  - rm .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
    condition: $NODE_MAIN = true
